replaced nginx with minio

diff --git a/ap-tools b/ap-tools
--- a/ap-tools
+++ b/ap-tools
@@ -23,22 +23,27 @@ LAST_NAME=changeme
 USERNAME=administrator
 EMAIL=changeme@example.com
 
-# --- USER DEFINED Harbor and NGINX Configuration --- #
+# --- USER DEFINED Harbor and MINIO Configuration --- #
 HARBOR_VERSION=2.12.2
 HARBOR_PORT=443
 HARBOR_USERNAME=admin
 HARBOR_PASSWORD=Harbor12345
-NGINX_HTUSER=admin
-NGINX_HTPASS=changeme
-NGINX_PORT=4443
+MINIO_ROOT_USER=admin
+MINIO_ROOT_PASSWORD=changeme
+MINIO_S3_PORT=9000
+MINIO_CONSOLE_PORT=9001
+MINIO_VERSION=latest
+MINIO_CLIENT_VERSION=latest
+MINIO_DEFAULT_BUCKET=default-bucket
 
-# --- USER DEFINED Self-Signed Certificate Configuration for Harbor and NGINX --- #
+# --- USER DEFINED Self-Signed Certificate Configuration for Harbor and MinIO --- #
 COUNTRY=US
 STATE=MA
 LOCATION=HOPKINTON
 ORGANIZATION=DELL
-NGINX_COMMON_NAME=artifacts.edge.lab
 HARBOR_COMMON_NAME=registry.edge.lab
+MINIO_FQDN=minio.edge.lab
+MINIO_WILDCARD_DOMAIN=*.edge.lab
 DURATION_DAYS=3650
 
 # --- USER DEFINED Kubernetes Configuration ---#
@@ -106,7 +111,7 @@ kb_000216838_file="https://supportkb.dell.com/attachment/ka0Do000000Sb4oIAC/logs
 
 usage() {
     cat << EOF
-Usage: \$SCRIPT_NAME [install rke2|ap-bundle|harbor|nginx] [offline-prep] [push] [join server|agent [server-fqdn] [join-token-string]] [-tls-san [server-fqdn-ip]] [-registry [registry:port username password]]
+Usage: \$SCRIPT_NAME [install rke2|ap-bundle|harbor|minio] [offline-prep] [push] [join server|agent [server-fqdn] [join-token-string]] [-tls-san [server-fqdn-ip]] [-registry [registry:port username password]]
 
 Commands:
   install      : Installs specified component and any dependencies.
@@ -115,7 +120,7 @@ Commands:
     [ap-bundle]  Extracts the Dell Automation Platform install bundle and outputs the install command.
                  Must be used with [-registry].
     [harbor]     Installs the harbor registry.
-    [nginx]      Installs an nginx static file server.
+    [minio]      Installs a single-node minio server and default bucket.
 
   offline-prep : Creates an offline tar package which contains all dependencies for an air-gapped installation.
                  Cannot be used with [install] [push] [join].
@@ -288,18 +293,18 @@ run_install_join_push () {
   fi
 }
 
-run_install_nginx () {
-  cd $WORKING_DIR/ap-utilities/nginx
+run_install_minio () {
+  cd $WORKING_DIR/ap-utilities/minio
   if [[ $AIR_GAPPED_MODE == "0" ]]; then
-      curl -OL https://github.com/Chubtoad5/nginx-static-files/raw/refs/heads/main/install_nginx.sh
-      chmod +x install_nginx.sh
-      INSTALL_SERVER=true OFFLINE_PREP=false NGINX_PORT=$NGINX_PORT NGINX_COMMON_NAME=$NGINX_COMMON_NAME NGINX_HTUSER=$NGINX_HTUSER NGINX_HTPASS=$NGINX_HTPASS DURATION_DAYS=$DURATION_DAYS STATE=$STATE COUNTRY=$COUNTRY LOCATION=$LOCATION ORGANIZATION=$ORGANIZATION DEBUG=$DEBUG ./install_nginx.sh
+    curl -kL https://github.com/Chubtoad5/minio-installer/raw/refs/heads/main/minio-installer -o $WORKING_DIR/ap-utilities/minio/minio-installer &>/dev/null || true
+    chmod +x minio-installer
   else
-      for file in "$WORKING_DIR/ap-utilities/nginx/nginx_offline_install-*.tar.gz"; do
-        tar xzf $file
-      done
-      INSTALL_SERVER=true OFFLINE_PREP=true NGINX_PORT=$NGINX_PORT NGINX_COMMON_NAME=$NGINX_COMMON_NAME NGINX_HTUSER=$NGINX_HTUSER NGINX_HTPASS=$NGINX_HTPASS DURATION_DAYS=$DURATION_DAYS STATE=$STATE COUNTRY=$COUNTRY LOCATION=$LOCATION ORGANIZATION=$ORGANIZATION DEBUG=$DEBUG ./install_nginx.sh
+    for file in "$WORKING_DIR/ap-utilities/minio/minio-save.tar.gz"; do
+      tar xzf $file
+    done
   fi
+  MINIO_ROOT_USER=$MINIO_ROOT_USER MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD MINIO_S3_PORT=$MINIO_S3_PORT MINIO_CONSOLE_PORT=$MINIO_CONSOLE_PORT MINIO_VERSION=$MINIO_VERSION MINIO_CLIENT_VERSION=$MINIO_CLIENT_VERSION MINIO_DEFAULT_BUCKET=$MINIO_DEFAULT_BUCKET COUNTRY=$COUNTRY STATE=$STATE LOCATION=$LOCATION ORGANIZATION=$ORGANIZATION MINIO_FQDN=$MINIO_FQDN MINIO_WILDCARD_DOMAIN=$MINIO_WILDCARD_DOMAIN DURATION_DAYS=$DURATION_DAYS DEBUG=$DEBUG ./minio-installer install
+  cd $base_dir
 }
 
 run_install_harbor () {
@@ -541,8 +546,8 @@ run_offline_prep () {
     echo "--- Starting offline preparation workflow"
     echo "  Downloading host packages..."
     run_debug download_ap_packages
-    echo "  Downloading NGINX binaries..."
-    run_debug download_nginx
+    echo "  Downloading MinIO binaries..."
+    run_debug download_minio
     echo "  Downloading Harbor binaries..."
     run_debug download_harbor
     echo "  Downloading dependancy helm charts..."
@@ -562,12 +567,11 @@ run_offline_prep () {
     echo "--- Offline prep workflow complete"
 }
 
-download_nginx () {
-  cp $WORKING_DIR/ap-utilities/packages/install_packages.sh $WORKING_DIR/ap-utilities/nginx/nginx
-  cd $WORKING_DIR/ap-utilities/nginx
-  curl -OL https://github.com/Chubtoad5/nginx-static-files/raw/refs/heads/main/install_nginx.sh
-  chmod +x install_nginx.sh
-  INSTALL_SERVER=true OFFLINE_PREP=true ./install_nginx.sh
+download_minio () {
+  curl -kL https://github.com/Chubtoad5/minio-installer/raw/refs/heads/main/minio-installer -o $WORKING_DIR/ap-utilities/minio/minio-installer
+  chmod +x $WORKING_DIR/ap-utilities/minio/minio-installer
+  cd $WORKING_DIR/ap-utilities/minio
+  ./minio-installer save
   cd $base_dir
 }
 
@@ -770,7 +774,7 @@ create_working_dir () {
     [ -d "$WORKING_DIR" ] || mkdir -p "$WORKING_DIR"
     [ -d "$WORKING_DIR/ap-utilities/packages" ] || mkdir -p "$WORKING_DIR/ap-utilities/packages"
     [ -d "$WORKING_DIR/ap-utilities/harbor" ] || mkdir -p "$WORKING_DIR/ap-utilities/harbor"
-    [ -d "$WORKING_DIR/ap-utilities/nginx/nginx" ] || mkdir -p "$WORKING_DIR/ap-utilities/nginx/nginx"
+    [ -d "$WORKING_DIR/ap-utilities/minio" ] || mkdir -p "$WORKING_DIR/ap-utilities/minio"
     [ -d "$WORKING_DIR/ap-utilities/helm/haproxy" ] || mkdir -p "$WORKING_DIR/ap-utilities/helm/haproxy"
     [ -d "$WORKING_DIR/ap-utilities/helm/metallb" ] || mkdir -p "$WORKING_DIR/ap-utilities/helm/metallb"
     [ -d "$WORKING_DIR/ap-utilities/helm/longhorn" ] || mkdir -p "$WORKING_DIR/ap-utilities/helm/longhorn"
@@ -1013,10 +1017,10 @@ while [[ "$#" -gt 0 ]]; do
         install)
             INSTALL_MODE=1
             INSTALL_TYPE="${2:-}"
-            if [[ -z "$INSTALL_TYPE" || "$INSTALL_TYPE" != "ap-bundle" && "$INSTALL_TYPE" != "rke2" && "$INSTALL_TYPE" != "harbor" && "$INSTALL_TYPE" != "nginx" ]]; then
+            if [[ -z "$INSTALL_TYPE" || "$INSTALL_TYPE" != "ap-bundle" && "$INSTALL_TYPE" != "rke2" && "$INSTALL_TYPE" != "harbor" && "$INSTALL_TYPE" != "minio" ]]; then
             # if [[ -z "$INSTALL_TYPE" || ("$INSTALL_TYPE" != "rke2" && "$INSTALL_TYPE" != "ap-bundle") ]]; then
-                # echo "Error: 'install' command requires an install type. Format: install [rke2|ap-bundle|harbor|nginx]"
-                echo "Error: 'install' command requires an install type. Format: install [rke2|ap-bundle|harbor|nginx]"
+                # echo "Error: 'install' command requires an install type. Format: install [rke2|ap-bundle|harbor|minio]"
+                echo "Error: 'install' command requires an install type. Format: install [rke2|ap-bundle|harbor|minio]"
                 echo "Type './$SCRIPT_NAME -h' for help."
                 exit 1
             fi
@@ -1173,7 +1177,7 @@ if [[ $OFFLINE_PREP_MODE == "1" ]]; then
   run_offline_prep
   echo "Offline archive 'ap-offline.tar.gz' created. Copy the archive to an air-gapped host running the same version of $OS_ID"
 fi
-if [[ ($INSTALL_MODE == "1" || $JOIN_MODE == "1" || $PUSH_MODE == "1") && ($INSTALL_TYPE != "ap-bundle" && $INSTALL_TYPE != "harbor" && $INSTALL_TYPE != "nginx") ]]; then
+if [[ ($INSTALL_MODE == "1" || $JOIN_MODE == "1" || $PUSH_MODE == "1") && ($INSTALL_TYPE != "ap-bundle" && $INSTALL_TYPE != "harbor" && $INSTALL_TYPE != "minio") ]]; then
   [[ $TLS_SAN_MODE == "0" ]] || dns_pre_flight_checks $TLS_SAN
   [[ $REGISTRY_MODE == "0" ]] || dns_pre_flight_checks $REG_FQDN
   run_install_join_push
@@ -1186,9 +1190,9 @@ if [[ $INSTALL_TYPE == "ap-bundle" ]]; then
   ap_preflight_checks
   ap_bundle_prep
 fi
-if [[ $INSTALL_TYPE == "nginx" ]]; then
-  echo "  Installing NGINX artifact server..."
-  run_install_nginx
+if [[ $INSTALL_TYPE == "minio" ]]; then
+  echo "  Installing MinIO artifact server..."
+  run_install_minio
 fi
 if [[ $INSTALL_TYPE == "harbor" ]]; then
   echo "  Installing Harbor registry..."
